FROM 1c_ext_ubuntu
EXPOSE 5432
USER postgres
CMD ["/usr/lib/postgresql/9.2/bin/postgres", "-D", "/var/lib/postgresql/9.2/main", "-c", "config_file=/etc/postgresql/9.2/main/postgresql.conf"]
# CMD '/etc/init.d/postgresql start'
