
  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: localhost
    timeout: 5000
    username: postgres
    password: Lee6eetu


  development:
    <<: *default
    database: uk_development

  test:
    <<: *default
    database: uk_test

  production:
    <<: *default
    database: uk_production
