  uk_external_development:
    adapter:  sqlserver
    host:     176.112.198.251
    encoding: unicode
    database: uhp_demo1
    pool:     5
    username: sa
    password: kpa64Mys

  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: localhost
    timeout: 5000
    username: postgres
    password: Lee6eetu


  development:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: uk_development
    pool:     5
    username: postgres
    password:

  test:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: uk_test
    pool:     5
    username: postgres
    password:

  production:
    <<: *default
    database: uk_production
    password: 4fV6DkNt9n
