  uk_external_development:
    adapter:  postgresql
    host:     192.168.99.100
    port: 5432
    encoding: unicode
    database: uhp_demo
    pool:     5
    username: postgres
    password: vault13

  default: &default
    adapter: postgresql
    encoding: unicode
    pool: 5
    host: localhost
    timeout: 5000
    username: postgres
    password: Lee6eetu


  development:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: uk_development
    pool:     5
    username: postgres
    password:

  test:
    adapter:  postgresql
    host:     localhost
    encoding: unicode
    database: uk_test
    pool:     5
    username: postgres
    password:

  production:
    <<: *default
    database: uk_production
    password: 4fV6DkNt9n
